/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ken.norightturns;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Play classUnderTest = new Play();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
