/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ken.norightturns;

import org.junit.Test;

import com.ken.norightturns.analysis.Explore_ShortestPath;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Explore_ShortestPath classUnderTest = new Explore_ShortestPath();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
